### ISSUE TITLE
No training config

### ISSUE THREAD

**Issue by amootta** [Illumina/SpliceAI#88]
Hi, I've been having some problems with running the programme. I'm on python 3.7 - have keras v.2.3.1, Tensorflow v.1.9.0 and h5py version 2.10.0. I am getting the same error:
Using TensorFlow backend.
2021-11-08 21:50:22.893413: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-08 21:50:22.904246: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000000000 Hz
2021-11-08 21:50:22.906847: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55cf098c7c50 executing computations on platform Host. Devices:
2021-11-08 21:50:22.906882: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): Host, Default Version
2021-11-08 21:50:22.915940: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
/home/am3u20/.conda/envs/spliceai_3.7/lib/python3.7/site-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was not compiled. Compile it manually.

I've trialled it with the example input.vcf provided, and the output basically has no annotations as is to be expected in the example output provided. Please let me know what else I can try to fix this error! Thanks very much

**Comment by kishorejaganathan** [comment]
There seems to be some compatibility issues with python 3.7, thank you for bringing this to my attention. I will send out a fix later this month. Meanwhile, I have checked that everything works fine with python 3.6.

**Comment by amootta** [comment]
Hi,
Thanks very much for your reply. I tried using python 3.6 and the same versions of the other software required, i.e. keras v.2.3.1, Tensorflow v.1.9.0 and h5py version 2.10.0. But it's now giving me an error: 
Traceback (most recent call last):
  File "/home/am3u20/.conda/envs/spliceai/bin/spliceai", line 5, in <module>
    from spliceai.__main__ import main
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/spliceai/__main__.py", lin                                                                                e 5, in <module>
    from spliceai.utils import Annotator, get_delta_scores
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/spliceai/utils.py", line 6                                                                                , in <module>
    from keras.models import load_model
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/keras/__init__.py", line 3                                                                                , in <module>
    from . import utils
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/keras/utils/__init__.py",                                                                                 line 6, in <module>
    from . import conv_utils
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/keras/utils/conv_utils.py"                                                                                , line 9, in <module>
    from .. import backend as K
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/keras/backend/__init__.py"                                                                                , line 1, in <module>
    from .load_backend import epsilon
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/keras/backend/load_backend                                                                                .py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/am3u20/.conda/envs/spliceai/lib/python3.6/site-packages/keras/backend/tensorflow_b                                                                                ackend.py", line 54, in <module>
    get_graph = tf_keras_backend.get_graph
AttributeError: module 'tensorflow.python.keras.backend' has no attribute 'get_graph'

I then tried using different versions, i.e. Keras version 2.2.0 and tensorflow v 1.14.0, which lets it run, but similar error to the original one, where it does not add any annotations to the file. Which versions of keras/tensorflow/h5py did you get to have it working on python 3.6? 
Thanks very much

**Comment by kishorejaganathan** [comment]
Can you try with keras==2.0.5, tensorflow==1.9.0, h5py==2.10.0 in python 3.6?

**Comment by kdewispelaere** [comment]
Hi,
with these exact versions, this error persists for me (I also tried with pandas 0.25.3 and 1.1.5). Usin Keras 2.0.5, h5py 2.10 and tf 1.14.0, I did get an output file from the test input but only the headers and the error 
"UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file:" 
(all in python 3.6)
Hopefully you can help, I really want to try out your software
Kind regards,
Koen

**Comment by kdewispelaere** [comment]
I now see this issue had nothing to do with the training configuration. The reference nucleotides were wrong. I implemented the software with the versions above and pandas==1.1.5 but changed some things in the source code for it to work with an updated pandas. Works fine now, great stuff
